In [1]:
import pandas as pd
import matplotlib as plt
import numpy as np
import random

In [2]:
frame1=pd.DataFrame( {'id':['ball','pencil','pen','mug','ashtray'],'price': [12.33,11.44,33.21,13.23,33.62],'abc':[13,14,15,16,17]})
frame2=pd.DataFrame({'id':['ball','penicil','pen','ball','bat'],'color':['blue','black','red','green','yellow'],'material':['cotton','wool','nylon','plastic','fake'],'cost':[13,14,15,16,17]})

In [3]:
df=pd.merge(frame1,frame2,on='id')

In [4]:
df

id  price  abc  color material  cost
0  ball  12.33   13   blue   cotton    13
1  ball  12.33   13  green  plastic    16
2   pen  33.21   15    red    nylon    15

In [5]:
ok=pd.concat([frame1,frame2],axis=1)
ok

id  price  abc       id   color material  cost
0     ball  12.33   13     ball    blue   cotton    13
1   pencil  11.44   14  penicil   black     wool    14
2      pen  33.21   15      pen     red    nylon    15
3      mug  13.23   16     ball   green  plastic    16
4  ashtray  33.62   17      bat  yellow     fake    17

In [6]:
ser1=pd.Series(np.random.rand(4),index=[1,2,3,5])
ser2=pd.Series(np.random.rand(5),index=[2,4,6,7,8])

In [7]:
ser2[2:].combine_first(ser1[:3])

1    0.746868
2    0.375224
3    0.735267
6    0.616409
7    0.856533
8    0.624859
dtype: float64

In [8]:
ser1

1    0.746868
2    0.375224
3    0.735267
5    0.333156
dtype: float64

In [9]:
ser2

2    0.410348
4    0.994617
6    0.616409
7    0.856533
8    0.624859
dtype: float64

In [10]:
ser1.combine_first(ser2)

1    0.746868
2    0.375224
3    0.735267
4    0.994617
5    0.333156
6    0.616409
7    0.856533
8    0.624859
dtype: float64

In [11]:
d=frame1.stack()
f=d.unstack()

In [12]:
data = pd.DataFrame({'Subject': ['A', 'A', 'B', 'B', 'C', 'C'],
        'Variable': ['Height', 'Weight', 'Height', 'Weight', 'Height', 'Weight'],
        'Value': [160, 55, 175, 70, 162, 60]})

In [13]:
wide=data.pivot(index='Subject',columns='Variable',values='Value')

In [14]:
wide

Variable  Height  Weight
Subject                 
A            160      55
B            175      70
C            162      60

In [15]:
ok1=frame2.drop(frame2[frame2['color']=='blue'].index)

In [16]:
ok=frame2.set_index('id')

In [17]:
data=pd.DataFrame({'id':['ok','yes','yes','yes','no','no'],'value':[1,2,2,2,3,3]})

In [18]:
data.drop_duplicates()

id  value
0   ok      1
1  yes      2
4   no      3

In [19]:
frame1.rename(index={ 0 : 'zero',1:'first'})

id  price  abc
zero      ball  12.33   13
first   pencil  11.44   14
2          pen  33.21   15
3          mug  13.23   16
4      ashtray  33.62   17

In [20]:
q=frame1.rename(columns={'object':'ject'}, inplace=False)
q

id  price  abc
0     ball  12.33   13
1   pencil  11.44   14
2      pen  33.21   15
3      mug  13.23   16
4  ashtray  33.62   17

In [21]:
bins=[0,25,50,75,100]
results=[0,13,23,34,45,56,68,79,89,80,3,23,23,35,100]
cat=pd.qcut(results,4)

In [22]:
pd.value_counts(cat)

(-0.001, 23.0]    6
(73.5, 100.0]     4
(35.0, 73.5]      3
(23.0, 35.0]      2
Name: count, dtype: int64

In [23]:
cat.categories

IntervalIndex([(-0.001, 23.0], (23.0, 35.0], (35.0, 73.5], (73.5, 100.0]], dtype='interval[float64, right]')

In [25]:
herbf={'ball':'red','pencil':'blue','pen':'green','mug':'orange','ashtray':'yellow'}
a=frame1.replace(herbf)
a

id  price  abc
0     red  12.33   13
1    blue  11.44   14
2   green  33.21   15
3  orange  13.23   16
4  yellow  33.62   17

In [26]:
rec={'red':34,'blue':45,'green':56,'orange':67,'yellow':78}
a['price']=a['id'].map(rec)
a

id  price  abc
0     red     34   13
1    blue     45   14
2   green     56   15
3  orange     67   16
4  yellow     78   17

In [27]:
nframe = pd.DataFrame(np.arange(25).reshape(5,5))
print(nframe)
new_order = np.random.permutation(5)

print(new_order)
print(nframe.take([1,2,3,0]))

    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
[4 1 3 0 2]
    0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
0   0   1   2   3   4


In [28]:
randframe = pd.DataFrame(np.random.randn(1000,3))
avd=randframe[(np.abs(randframe) > (3*randframe.std())).any(axis=1)]
print(avd)
randframe.describe()

            0         1         2
794 -0.314731  0.458802 -3.184749


0            1            2
count  1000.000000  1000.000000  1000.000000
mean      0.010492     0.004608    -0.037266
std       0.989865     1.020100     0.985813
min      -2.611159    -3.020317    -3.184749
25%      -0.672382    -0.711614    -0.670406
50%       0.013830     0.021005    -0.024263
75%       0.712816     0.712428     0.599708
max       2.780350     3.027678     2.689452

In [29]:
np.random.permutation(8)

array([1, 4, 6, 7, 5, 2, 0, 3])

In [30]:
text = '16 Bolton Avenue , Boston'
abcd='eufr'

In [31]:
a=text.split(',')
a[0]

'16 Bolton Avenue '

In [32]:
frame = pd.DataFrame({ 'color': ['white','red','green','red','green'],'object': ['pen','pencil','pencil','ashtray','pen'],'price1' : [5.56,4.20,1.30,0.56,2.75],'price2' : [4.75,4.12,1.60,0.75,3.15]})

In [33]:
frame

color   object  price1  price2
0  white      pen    5.56    4.75
1    red   pencil    4.20    4.12
2  green   pencil    1.30    1.60
3    red  ashtray    0.56    0.75
4  green      pen    2.75    3.15

In [34]:
group = frame.groupby(frame['object'])
group['price1']
sums = frame.groupby('color').sum().add_prefix('tot_')
sums
frame.groupby('color').transform(np.sum).add_prefix('tot_')

tot_object  tot_price1  tot_price2
0            pen        5.56        4.75
1  pencilashtray        4.76        4.87
2      pencilpen        4.05        4.75
3  pencilashtray        4.76        4.87
4      pencilpen        4.05        4.75

In [35]:
def square(array):
    for i in range(len(array)):
        array[i]=array[i]*array[i]
array=[1,2,3,4]
square(array)
print(array)

[1, 4, 9, 16]


In [36]:
frame.groupby(['color','object']).apply( lambda x: x.max())

color   object  price1  price2
color object                                 
green pen      green      pen    2.75    3.15
      pencil   green   pencil    1.30    1.60
red   ashtray    red  ashtray    0.56    0.75
      pencil     red   pencil    4.20    4.12
white pen      white      pen    5.56    4.75

In [44]:
import sklearn.model_selection as ms
from sklearn.datasets import load_iris
iris=load_iris()
X = iris.data

Y = iris.target
XTrain, XTest, YTrain, YTest = ms.train_test_split(X, Y,  test_size= 0.3, random_state=7)

In [48]:
from sklearn import neighbors

from sklearn.model_selection import GridSearchCV
k_neighbours = list(range(1,21,2))

n_grid = [{'n_neighbors': k_neighbours}]

In [57]:
model = neighbors.KNeighborsClassifier()

cv_knn = GridSearchCV(estimator=model,param_grid=n_grid,cv=ms.KFold(n_splits=10))

cv_knn.fit(XTrain, YTrain)
best_k = cv_knn.best_params_['n_neighbors']

In [55]:
print('The best parameter is k={0}'.format(best_k))


The best parameter is k=11


In [81]:
arr=[1,2,3,4]
a=np.array(arr).reshape(2,2)

In [85]:
a=[[10,11,12],[13,14,15],[16,17,18]]
a=np.array(a)

In [99]:
A=np.arange(16).reshape(4,4)
[B,C]=np.hsplit(A,2)
B

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [106]:
b=A.shape[1]
c=A.shape[0]
arr=[]
arr2=[]

In [107]:
for a in range(b):
    for d in range(c):
        if(d>2):
            arr.append(A[a][d])
        else:
            arr2.append(A[a][d])

In [108]:
arr.reshape()

[3, 7, 11, 15]

In [109]:
a=[[10,11,12],[13,14,15],[16,17,18]]
b=np.array(a)