In [2]:
import torch

### Q1

In [3]:
tensor = torch.randn(2, 3)
print("Original ",tensor)
re= tensor.view(3, 2)
print("\nReshaped ",re)
vi = tensor.view(-1) 
print("\nViewed ",vi)
t1 = torch.randn(2, 3)
t2 = torch.randn(2, 3)
st= torch.stack([t1, t2], dim=0)
print("\nStacked ",st)
sq = tensor.squeeze()
print("\nSqueezed ",sq)
un = tensor.unsqueeze(0)
print("\nUnsqueezed ",un)

Original  tensor([[ 0.6845,  0.1263,  1.8317],
        [-0.5794,  0.9546, -0.4805]])

Reshaped  tensor([[ 0.6845,  0.1263],
        [ 1.8317, -0.5794],
        [ 0.9546, -0.4805]])

Viewed  tensor([ 0.6845,  0.1263,  1.8317, -0.5794,  0.9546, -0.4805])

Stacked  tensor([[[ 1.8348,  1.8574, -0.6521],
         [ 0.0185, -0.5179,  1.2557]],

        [[-0.1589,  1.0716, -0.2319],
         [ 1.0033, -0.1226, -0.0318]]])

Squeezed  tensor([[ 0.6845,  0.1263,  1.8317],
        [-0.5794,  0.9546, -0.4805]])

Unsqueezed  tensor([[[ 0.6845,  0.1263,  1.8317],
         [-0.5794,  0.9546, -0.4805]]])


### Q2

In [4]:
permuted_tensor = tensor.permute(1, 0)
print("\nPermuted",permuted_tensor)


Permuted tensor([[ 0.6845, -0.5794],
        [ 0.1263,  0.9546],
        [ 1.8317, -0.4805]])


### Q3

In [5]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original ",tensor)
i=tensor[0,2]
print('index ',i)

Original  tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
index  tensor(3)


### Q4

In [8]:
import numpy as np
n=np.array([[1,2,3],[4,5,6]])
print(n)
te=torch.from_numpy(n)
print('np->te',te)
np_b=te.numpy()
print('te->np',np_b)

[[1 2 3]
 [4 5 6]]
np->te tensor([[1, 2, 3],
        [4, 5, 6]])
te->np [[1 2 3]
 [4 5 6]]


### Q5

In [9]:
ran = torch.randn(7, 7)
print(ran)

tensor([[ 0.0578, -1.1934,  0.4811,  1.1300,  1.5266, -1.5101, -1.5977],
        [-0.9811, -0.7453,  0.0861, -1.4361,  1.1553,  2.2529, -0.3537],
        [-0.7630, -0.4877,  1.3133,  1.3334, -1.3079,  0.0545,  0.3248],
        [ 1.6005, -0.6533, -1.9406, -0.0396,  1.3271, -1.3730, -0.1591],
        [ 2.0043,  0.5643, -0.0540,  0.7872, -0.0045, -1.0447,  0.5429],
        [-0.2311, -1.2222,  0.0759,  0.8515,  0.5707,  0.3192,  0.8365],
        [ 1.6149, -0.0311,  1.8289,  0.3364, -0.5149, -1.5033, -0.4426]])


### Q6

In [10]:
tensor2 = torch.randn(1, 7)
result = torch.matmul(ran, tensor2.T),
print(result)

Result of matrix multiplication:
tensor([[ 0.3184],
        [-7.8056],
        [-0.1065],
        [ 0.8896],
        [ 4.7533],
        [-3.2453],
        [ 4.4489]])


### Q7

In [11]:
d = torch.device("cuda" if torch.cuda.is_available() else "cpu")
a = torch.randn(2, 3)
b = torch.randn(2, 3)
a = a.to(d)
b = b.to(d)
print("a on:", a.device)
print(a)
print("\nb on:", b.device)
print(b)


a on: cpu
tensor([[ 1.1465, -1.9663,  1.3578],
        [-0.2934,  1.1299,  1.3527]])

b on: cpu
tensor([[-0.2314,  1.1843,  0.1483],
        [-0.7636,  1.1770, -2.2765]])


/home/student/myenv/lib/python3.12/site-packages/torch/cuda/__init__.py:129: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0


### Q8

In [13]:
re = torch.matmul(a, b.T) 
print(re)

tensor([[-2.3927, -6.2810],
        [ 1.6067, -1.5255]])


### Q9

In [15]:
print('max val',torch.max(re))
print('min val',torch.min(re))

max val tensor(1.6067)
min val tensor(-6.2810)


### Q10

In [16]:
print('max val index',torch.argmax(re))
print('min val index',torch.argmin(re))

max val index tensor(2)
min val index tensor(1)


### Q11

In [17]:
torch.manual_seed(7)
t = torch.randn(1, 1, 1, 10)
t2 = t.squeeze()
print(t, t.shape)
print(t2, t2.shape)

tensor([[[[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,
            1.2324,  0.1382, -1.6822]]]]) torch.Size([1, 1, 1, 10])
tensor([-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,  1.2324,
         0.1382, -1.6822]) torch.Size([10])
