In [34]:
import numpy as np
import random

In [5]:
Assign1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
Assign1=np.reshape(Assign1,(3,3),'c')
Assign1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
Assign2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Assign2[Assign2%2==1]=-1
Assign2

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [20]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
desired1=np.where(x>y)
desired2=np.where(x==y)
desired1,desired2

((array([1, 2, 4, 5, 6, 7, 8, 9]),), (array([0]),))

In [30]:
Assign4= np.arange(100).reshape(5,-1)
Assign4[:,:4]

array([[ 0,  1,  2,  3],
       [20, 21, 22, 23],
       [40, 41, 42, 43],
       [60, 61, 62, 63],
       [80, 81, 82, 83]])

In [49]:
np.random.randint(low=30,high=41,size=10,dtype=int)

array([36, 37, 38, 36, 35, 39, 34, 38, 37, 34])

In [89]:
A=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]])
B=np.array([[7, 8, 10] ,[4, 5, 6], [1, 2, 3]])
C=A+B
E=A-B
C,E

(array([[ 8, 10, 13],
        [ 8, 10, 12],
        [ 8, 10, 13]]),
 array([[-6, -6, -7],
        [ 0,  0,  0],
        [ 6,  6,  7]]))

In [90]:
np.sum(A),np.sum(B,axis=0),np.sum(C,axis=1)

(46, array([12, 15, 19]), array([31, 30, 31]))

In [91]:
D=A@B
D

array([[ 18,  24,  31],
       [ 54,  69,  88],
       [ 91, 116, 148]])

In [92]:
E=np.reshape(C,(9),'c')
E.sort()

In [98]:
E=E.reshape((3,3))
E

array([[ 8,  8,  8],
       [10, 10, 10],
       [12, 13, 13]])

In [99]:
E.transpose()

array([[ 8, 10, 12],
       [ 8, 10, 13],
       [ 8, 10, 13]])